import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.text.Text;
import javafx.stage.Stage;
/**
 * Controller class for the Instructor Login view.
 * Manages user interactions in the instructor login screen, including logging out
 * and displaying the logged-in instructor's username.
 */
public class InstructorLoginController {
	private Stage stage;
	private Scene scene;
	private Parent root;
	private Storage storage;
	/** Text label that displays the logged-in instructor's username. */
	@FXML
	private Text ip_userLabel;
	   /**
     * Handles the event triggered by the instructor clicking the "Logout" button.
     * Logs the instructor out and redirects them back to the main scene.
     *
     * @param event The action event generated by clicking the logout button.
     * @throws IOException If the FXML file for the main scene cannot be loaded.
     */
	@FXML
	public void ip_logoutClicked(ActionEvent event) throws IOException{
		// Load the MainScene.fxml file and set it as the root of the new scene
		FXMLLoader loader = new FXMLLoader(getClass().getResource("MainScene.fxml"));
		root = loader.load();
	// Get the current stage and update the scene to the main scene	
        stage = (Stage)((Node)event.getSource()).getScene().getWindow();
        scene = new Scene(root);
        stage.setScene(scene);
        stage.show();
	}
	  /**
     * Sets the username of the instructor and updates the username label in the view.
     * This method is called to display the current user's name on the login screen.
     *
     * @param name The instructor's name to display.
     */
	public void userName(String name) {
		this.ip_userLabel.setText("User: " + name);
	}
}
